#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 The Linux Foundation
##############################################################################
# ZeroClaw Mission Control — Bootstrap Setup
# Generates secure tokens, creates .env, sets permissions
##############################################################################

set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${PROJECT_ROOT}/docker/.env"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

function log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

function log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

function log_error() {
    echo -e "${RED}[ERROR]${NC} $1" >&2
}

function generate_token() {
    openssl rand -hex 32
}

function generate_password() {
    openssl rand -base64 24 | tr -d '/+=' | head -c 32
}

function check_dependencies() {
    local missing=()
    for cmd in openssl docker; do
        if ! command -v "${cmd}" &>/dev/null; then
            missing+=("${cmd}")
        fi
    done

    if [[ ${#missing[@]} -gt 0 ]]; then
        log_error "Missing required tools: ${missing[*]}"
        log_error "Install them and re-run this script."
        exit 1
    fi

    if ! docker compose version &>/dev/null; then
        log_error "docker compose plugin not found."
        log_error "Install Docker Compose v2: https://docs.docker.com/compose/install/"
        exit 1
    fi
}

function create_env_file() {
    if [[ -f "${ENV_FILE}" ]]; then
        log_warn ".env already exists at ${ENV_FILE}"
        log_warn "To regenerate, delete it first or use scripts/rotate-secrets.sh"
        return 0
    fi

    local gateway_token
    local redis_password
    gateway_token="$(generate_token)"
    redis_password="$(generate_password)"

    cat > "${ENV_FILE}" <<EOF
# ZeroClaw Mission Control — Environment Configuration
# Generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# ⚠️  DO NOT COMMIT THIS FILE — it is gitignored

# ─── API Provider Keys ───────────────────────────────────────────
# Option 1: OpenRouter (RECOMMENDED — single key for all models)
#   Get key at: https://openrouter.ai/keys
OPENROUTER_API_KEY=

# Option 2: Direct provider keys (optional)
ANTHROPIC_API_KEY=
OPENAI_API_KEY=
BRAVE_API_KEY=

# Option 3: Google Gemini free tier
#   Get key at: https://aistudio.google.com/apikey
GOOGLE_API_KEY=

# ─── Internal Tokens (auto-generated — do not share) ─────────────
ZEROCLAW_GATEWAY_TOKEN=${gateway_token}
REDIS_PASSWORD=${redis_password}

# ─── Service Configuration ───────────────────────────────────────
# Bind to localhost only (secure) or 0.0.0.0 (accessible from LAN)
GATEWAY_BIND_HOST=127.0.0.1
DASHBOARD_BIND_HOST=127.0.0.1

# Ports
GATEWAY_PORT=18789
DASHBOARD_PORT=4000
EOF

    chmod 600 "${ENV_FILE}"
    log_info "Created ${ENV_FILE} with secure permissions (600)"
    log_info "Gateway token: ${gateway_token:0:8}...${gateway_token: -8} (truncated)"
    log_info "Redis password: (hidden)"
}

function create_workspace() {
    local workspace="${PROJECT_ROOT}/workspace"
    mkdir -p "${workspace}"
    mkdir -p "${PROJECT_ROOT}/data/usage"
    log_info "Created workspace and data directories"
}

function bootstrap_gateway_config() {
    local config_dir="${PROJECT_ROOT}/config/gateway"
    local config_file="${config_dir}/openclaw.json"
    local template="${config_dir}/openclaw.json.example"

    if [[ -f "${config_file}" ]]; then
        log_warn "openclaw.json already exists — skipping bootstrap"
        log_warn "To regenerate from template: cp ${template} ${config_file}"
        return 0
    fi

    if [[ ! -f "${template}" ]]; then
        log_error "Template not found: ${template}"
        return 1
    fi

    cp "${template}" "${config_file}"
    chmod 600 "${config_file}"
    log_info "Created openclaw.json from template (mode 600)"
    log_info "Secrets use \$VAR references — resolved from secrets.json at runtime"

    # Create empty secrets.json if missing
    local secrets_file="${config_dir}/secrets.json"
    if [[ ! -f "${secrets_file}" ]]; then
        cat > "${secrets_file}" <<SECRETS
{
  "TELEGRAM_BOT_TOKEN": "PASTE_FROM_BOTFATHER",
  "DISCORD_BOT_TOKEN": "PASTE_FROM_DISCORD_DEVELOPER_PORTAL"
}
SECRETS
        chmod 600 "${secrets_file}"
        log_info "Created secrets.json template (mode 600)"
        log_warn "Edit secrets.json with your actual bot tokens before starting"
    fi
}

function set_permissions() {
    chmod +x "${SCRIPT_DIR}"/*.sh
    log_info "Set execute permissions on all scripts"
}

function verify_setup() {
    local errors=0

    if [[ ! -f "${ENV_FILE}" ]]; then
        log_error ".env file not found"
        errors=$((errors + 1))
    fi

    if [[ -f "${ENV_FILE}" ]]; then
        local perms
        perms="$(stat -c '%a' "${ENV_FILE}" 2>/dev/null || stat -f '%Lp' "${ENV_FILE}" 2>/dev/null)"
        if [[ "${perms}" != "600" ]]; then
            log_warn ".env permissions are ${perms}, expected 600"
        fi
    fi

    if [[ ${errors} -gt 0 ]]; then
        log_error "Setup verification failed with ${errors} error(s)"
        return 1
    fi

    log_info "Setup verification passed ✅"
}

function main() {
    echo ""
    echo "╔══════════════════════════════════════════════════╗"
    echo "║   ZeroClaw Mission Control — Setup              ║"
    echo "║   Zero-Trust Agent Orchestration Platform       ║"
    echo "╚══════════════════════════════════════════════════╝"
    echo ""

    log_info "Checking dependencies..."
    check_dependencies

    log_info "Generating secure credentials..."
    create_env_file

    log_info "Creating workspace..."
    create_workspace

    log_info "Bootstrapping gateway config..."
    bootstrap_gateway_config

    log_info "Setting permissions..."
    set_permissions

    log_info "Verifying setup..."
    verify_setup

    echo ""
    log_info "Setup complete! Next steps:"
    echo "  1. Edit docker/.env and add at least ONE API key:"
    echo "     - OPENROUTER_API_KEY (recommended — single key for all models)"
    echo "       Get free key: https://openrouter.ai/keys"
    echo "     - GOOGLE_API_KEY (free tier: https://aistudio.google.com/apikey)"
    echo "     - ANTHROPIC_API_KEY / OPENAI_API_KEY (if you have them)"
    echo "  2. Start services:"
    echo "     cd docker && docker compose up -d"
    echo "  3. Check health:"
    echo "     ./scripts/health-check.sh"
    echo ""
}

main "$@"
