# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 The Linux Foundation
# SearXNG settings — self-hosted metasearch for ZeroClaw agents
# Docs: https://docs.searxng.org/admin/settings.html

use_default_settings: true

general:
  instance_name: "ZeroClaw Search"
  debug: false
  privacypolicy_url: false
  contact_url: false

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "en"
  formats:
    - html
    - json

server:
  secret_key: "78453efdc7e56ffe44ec12b3100efa330a024b4a96dc81006685cdbc2975075d"
  bind_address: "0.0.0.0"
  port: 8080
  limiter: false
  image_proxy: false
  public_instance: false

ui:
  static_use_hash: true
  default_theme: simple

engines:
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false

  - name: google
    engine: google
    shortcut: g
    disabled: false

  - name: bing
    engine: bing
    shortcut: b
    disabled: false

  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    disabled: false

  - name: github
    engine: github
    shortcut: gh
    disabled: false

  - name: stackoverflow
    engine: stackoverflow
    shortcut: so
    disabled: false

  - name: arxiv
    engine: arxiv
    shortcut: arx
    disabled: false

  - name: brave
    engine: brave
    shortcut: br
    disabled: false
